# Generated by Django 3.2 on 2021-06-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_direction', models.CharField(choices=[('PAY', 'PAY'), ('REC', 'REC')], default='PAY', max_length=3)),
                ('dim1', models.CharField(blank=True, max_length=10, null=True)),
                ('dim2', models.CharField(blank=True, max_length=10, null=True)),
                ('dim4', models.CharField(blank=True, max_length=10, null=True)),
                ('pl_bs', models.CharField(choices=[('PL', 'PL'), ('BS', 'BS')], default='PL', max_length=2)),
                ('d_c_if_amount_positiv', models.CharField(choices=[('D', 'D'), ('C', 'C')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m3_brand_code', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=50)),
                ('transaction_direction', models.CharField(choices=[('PAY', 'PAY'), ('REC', 'REC')], default='PAY', max_length=3)),
                ('payment_terms', models.IntegerField()),
                ('mini_gar_status', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('minimum_guar_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('acc_month', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], max_length=2)),
                ('acc_year', models.CharField(max_length=10)),
                ('dashboard', models.BooleanField(default=False)),
                ('file_type', models.CharField(choices=[('accruals', 'accruals'), ('cash_forecast', 'cash_forecast'), ('partner_report', 'partner_report')], default='accruals', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('formula_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('formula_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_incl_excl', models.CharField(choices=[('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE')], default='INCLUDE', max_length=7)),
                ('country_list', models.CharField(blank=True, max_length=2000, null=True)),
                ('field_type', models.CharField(choices=[('RATE', 'RATE'), ('QTY', 'QTY')], default='RATE', max_length=7)),
                ('period_from', models.DateField(default='1900-01-01')),
                ('period_to', models.DateField(default='2999-01-01')),
                ('tranche_type', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=7)),
                ('rate_value', models.FloatField(blank=True, null=True)),
                ('qty_value', models.FloatField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_contract', to='royalty_app.contract')),
                ('country', models.ManyToManyField(blank=True, related_name='rule_country', to='royalty_app.Country')),
                ('formulation', models.ManyToManyField(related_name='rule_formulation', to='royalty_app.Formulation')),
                ('qty_value_currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='royalty_app.currency')),
                ('report_currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='rule_report_currency', to='royalty_app.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_breakdown_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_breakdown_definition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_payor', models.CharField(blank=True, max_length=10, null=True)),
                ('to_payee', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('amount_contract_curr', models.FloatField(blank=True, null=True)),
                ('wht_rate', models.FloatField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.FloatField(blank=True, null=True)),
                ('to_amount', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranche_rule', to='royalty_app.rule')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wht_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_from', to='royalty_app.country')),
                ('country_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_to', to='royalty_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_breakdown_per_contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_breakdown_contract_definition', models.CharField(max_length=50)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_breakdown_per_contract_contract', to='royalty_app.contract')),
                ('sales_breakdown_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_breakdown_per_contract_item', to='royalty_app.sales_breakdown_item')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_breakdown_for_contract_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('country_id', models.CharField(blank=True, max_length=10, null=True)),
                ('formulation', models.CharField(blank=True, max_length=10, null=True)),
                ('SKU', models.CharField(blank=True, max_length=10, null=True)),
                ('SKU_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_currency', models.CharField(blank=True, max_length=5, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('sales_breakdown_definition', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_breakdown_contract_definition', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_currency', models.CharField(blank=True, max_length=5, null=True)),
                ('sales_in_market_curr', models.FloatField(blank=True, null=True)),
                ('sales_in_contract_curr', models.FloatField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('country_id', models.CharField(blank=True, max_length=10, null=True)),
                ('SKU', models.CharField(blank=True, max_length=10, null=True)),
                ('SKU_name', models.CharField(blank=True, max_length=100, null=True)),
                ('formulation', models.CharField(max_length=6)),
                ('volume', models.BigIntegerField()),
                ('sales', models.FloatField(blank=True, null=True)),
                ('sales_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Rule_calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_incl_excl', models.CharField(blank=True, max_length=100, null=True)),
                ('country_list', models.CharField(blank=True, max_length=2000, null=True)),
                ('formulation', models.CharField(blank=True, max_length=100, null=True)),
                ('period_from', models.DateField(default='1900-01-01')),
                ('period_to', models.DateField(default='1900-01-01')),
                ('tranche_type', models.CharField(blank=True, max_length=3, null=True)),
                ('field_type', models.CharField(blank=True, max_length=10, null=True)),
                ('qty_value', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_rate', models.FloatField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicity_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity_cat', models.CharField(max_length=20)),
                ('period_month_end', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], max_length=2)),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodicity_structure', to='royalty_app.periodicity')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_month', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], max_length=2)),
                ('periodicity_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodicity_cat_structure', to='royalty_app.periodicity_cat')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_m3_code', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('ico_3rd', models.CharField(choices=[('3rd', '3rd'), ('ICO', 'ICO')], default='3rd', max_length=3)),
                ('partner_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_country', to='royalty_app.country')),
                ('partner_payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_payment_type', to='royalty_app.payment_type')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('year', models.CharField(max_length=10)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_contract', to='royalty_app.contract')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_partner', to='royalty_app.partner')),
                ('periodicity_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_periodicity_cat', to='royalty_app.periodicity_cat')),
            ],
        ),
        migrations.CreateModel(
            name='Gls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('accountingdate', models.CharField(blank=True, max_length=50, null=True)),
                ('reverseDate', models.CharField(blank=True, max_length=50, null=True)),
                ('dim1', models.CharField(blank=True, max_length=50, null=True)),
                ('dim2', models.CharField(blank=True, max_length=50, null=True)),
                ('dim3', models.CharField(blank=True, max_length=50, null=True)),
                ('dim4', models.CharField(blank=True, max_length=50, null=True)),
                ('accruals_contract_curr', models.FloatField(blank=True, null=True)),
                ('d_c', models.CharField(blank=True, max_length=10, null=True)),
                ('text_voucherline', models.CharField(blank=True, max_length=100, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Fx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=50)),
                ('division_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='royalty_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('division_country_id', models.CharField(blank=True, max_length=10, null=True)),
                ('division_via', models.CharField(blank=True, max_length=10, null=True)),
                ('field_type', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_sales', models.CharField(max_length=10)),
                ('month_of_sales', models.CharField(blank=True, max_length=2, null=True)),
                ('SKU', models.CharField(blank=True, max_length=10, null=True)),
                ('SKU_name', models.CharField(blank=True, max_length=100, null=True)),
                ('market_id', models.CharField(blank=True, max_length=10, null=True)),
                ('sales_in_market_curr', models.FloatField(blank=True, null=True)),
                ('sales_in_contract_curr', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('market_curr', models.CharField(blank=True, max_length=10, null=True)),
                ('sales_rate', models.FloatField(blank=True, null=True)),
                ('qty_value', models.FloatField(blank=True, null=True)),
                ('beneficiary_percentage', models.FloatField(blank=True, null=True)),
                ('amount_contract_curr', models.FloatField(blank=True, null=True)),
                ('transaction_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('amount_consolidation_curr', models.FloatField(blank=True, null=True)),
                ('Consolidation_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_id', models.PositiveSmallIntegerField()),
                ('contract_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_id', models.PositiveSmallIntegerField()),
                ('ico_3rd', models.CharField(blank=True, max_length=3, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_country_id', models.CharField(blank=True, max_length=10, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('m3_brand_code', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_paid', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(default='1900-01-01')),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='country_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_region', to='royalty_app.region'),
        ),
        migrations.CreateModel(
            name='Contract_partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.contract')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='royalty_app.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_currency', to='royalty_app.currency'),
        ),
        migrations.AddField(
            model_name='contract',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_division', to='royalty_app.division'),
        ),
        migrations.AddField(
            model_name='contract',
            name='division_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_division_via', to='royalty_app.division'),
        ),
        migrations.AddField(
            model_name='contract',
            name='m3_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='m3_brand', to='royalty_app.brand'),
        ),
        migrations.AddField(
            model_name='contract',
            name='minimum_guar_remaining_allocation_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minimum_guar_remaining_allocation_country', to='royalty_app.country'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_periodicity', to='royalty_app.periodicity'),
        ),
        migrations.CreateModel(
            name='Consolidation_currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='royalty_app.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Conso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_sales', models.CharField(max_length=10)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('consolidation_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('amount_consolidation_curr', models.FloatField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_paid', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_date', models.DateField(default='1900-01-01')),
                ('amount_contract_curr', models.FloatField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_app.file')),
            ],
        ),
    ]
