# Generated by Django 3.2 on 2021-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_picture',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user_profile_picture',
            name='profile_pic',
            field=models.ImageField(blank=True, default='royalty_app/static/default.png', null=True, upload_to=''),
        ),
    ]
