# Generated by Django 3.2 on 2021-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_calc',
            name='formulation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='formulation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales_breakdown_for_contract_report',
            name='formulation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
