# Generated by Django 3.2 on 2021-07-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='mini_gar_from',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='contract',
            name='mini_gar_to',
            field=models.DateField(default='2100-01-01'),
        ),
    ]
