# Generated by Django 3.2 on 2021-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month_table_test',
            name='month_name',
        ),
        migrations.RemoveField(
            model_name='month_table_test',
            name='month_nb',
        ),
        migrations.AddField(
            model_name='month_table_test',
            name='periodicity',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
