# Generated by Django 3.2 on 2021-08-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='SKU',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='SKU_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
