# Generated by Django 3.2 on 2021-08-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='contract_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='royalty_app.type'),
            preserve_default=False,
        ),
    ]
