# Generated by Django 3.2 on 2021-07-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
    ]
