# Generated by Django 3.2 on 2021-08-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_accounting_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_entry',
            name='contract_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contract_type_acc_entr', to='royalty_app.type'),
            preserve_default=False,
        ),
    ]
