# Generated by Django 3.2 on 2021-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_auto_20210710_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='acc_year',
            field=models.IntegerField(),
        ),
    ]
