# Generated by Django 3.2 on 2021-07-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_picture',
            name='profile_picture',
            field=models.ImageField(default='royalty_app/static/default.png', upload_to='media/profile_picture/'),
        ),
    ]
