# Generated by Django 3.2 on 2021-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_auto_20210723_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conso',
            name='year_of_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='year_of_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fx',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rule_calc',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales_breakdown_for_contract_report',
            name='year',
            field=models.IntegerField(),
        ),
    ]
