# Generated by Django 3.2 on 2021-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_detail_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('SALES', 'SALES'), ('COGS', 'COGS'), ('ROYALTY', 'ROYALTY'), ('MARGIN', 'MARGIN')], default='ROYALTY', max_length=20),
        ),
    ]
