# Generated by Django 3.2 on 2021-08-02 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_auto_20210802_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='partner_id',
        ),
        migrations.AddField(
            model_name='detail',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='royalty_app.partner'),
            preserve_default=False,
        ),
    ]
