# Generated by Django 3.2 on 2021-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_auto_20210710_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='testestes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Month_table_test',
        ),
    ]
