# Generated by Django 3.2 on 2021-07-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0002_auto_20210717_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile_picture',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
