# Generated by Django 3.2 on 2021-08-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0003_accounting_entry_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_market', to='royalty_app.country'),
            preserve_default=False,
        ),
    ]
