# Generated by Django 3.2 on 2021-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0003_rename_consolidation_currency_detail_consolidation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='month_of_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='year_of_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule_calc',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
