# Generated by Django 3.2 on 2021-07-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0003_auto_20210724_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='month_of_sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales_breakdown_for_contract_report',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
