# Generated by Django 3.2 on 2021-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0003_rule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='rule_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
