# Generated by Django 3.2 on 2021-08-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0004_invoice_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_market', to='royalty_app.country'),
        ),
    ]
