# Generated by Django 3.2 on 2021-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0004_auto_20210724_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='mini_gar_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mini_gar_to',
            field=models.IntegerField(),
        ),
    ]
