# Generated by Django 3.2 on 2021-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0004_auto_20210725_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='SKU',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='SKU_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='contract_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='partner_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
