# Generated by Django 3.2 on 2021-07-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0004_alter_invoice_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_file',
            name='upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
