# Generated by Django 3.2 on 2021-08-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0005_alter_rule_report_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='report_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='rule_tranche_currency', to='royalty_app.currency'),
        ),
    ]
