# Generated by Django 3.2 on 2021-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0005_auto_20210725_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='payment_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
    ]
