# Generated by Django 3.2 on 2021-08-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0005_alter_invoice_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='dim4',
            new_name='market_acc',
        ),
        migrations.RenameField(
            model_name='accounting_entry',
            old_name='dim4',
            new_name='market_acc',
        ),
    ]
