# Generated by Django 3.2 on 2021-07-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0005_auto_20210724_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='mini_gar_from',
            field=models.IntegerField(default=1900),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mini_gar_to',
            field=models.IntegerField(default=2100),
        ),
    ]
