# Generated by Django 3.2 on 2021-07-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0006_alter_detail_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='qty_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sales_in_contract_curr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sales_in_market_curr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='volume',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
