# Generated by Django 3.2 on 2021-07-13 12:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0006_alter_user_profile_picture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_picture',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='royalty_app/static/default.png', force_format=None, keep_meta=True, quality=10, size=[1920, 1080], upload_to='media/profile_picture/'),
        ),
    ]
