# Generated by Django 3.2 on 2021-08-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0006_auto_20210809_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='dim1',
            new_name='account_nb',
        ),
        migrations.RenameField(
            model_name='accounting',
            old_name='dim2',
            new_name='cost_center_acc',
        ),
        migrations.RenameField(
            model_name='accounting_entry',
            old_name='dim1',
            new_name='account_nb',
        ),
        migrations.RenameField(
            model_name='accounting_entry',
            old_name='dim2',
            new_name='cost_center_acc',
        ),
    ]
