# Generated by Django 3.2 on 2021-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0007_auto_20210725_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wht',
            name='contract_currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wht',
            name='from_payor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wht',
            name='to_payee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wht',
            name='wht_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
