# Generated by Django 3.2 on 2021-07-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0008_auto_20210718_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='period_to',
            field=models.DateField(default='2100-01-01'),
        ),
    ]
