# Generated by Django 3.2 on 2021-07-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0009_alter_rule_period_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule_calc',
            name='year_rule',
        ),
    ]
