# Generated by Django 3.2 on 2021-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0010_remove_rule_calc_year_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule_calc',
            name='period_from',
        ),
        migrations.RemoveField(
            model_name='rule_calc',
            name='period_to',
        ),
        migrations.AddField(
            model_name='rule_calc',
            name='year_rule',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
