# Generated by Django 3.2 on 2021-07-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0011_auto_20210718_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule_calc',
            name='period_from',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='rule_calc',
            name='period_to',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
