# Generated by Django 3.2 on 2021-07-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_app', '0012_auto_20210718_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule_calc',
            old_name='year_rule',
            new_name='year',
        ),
    ]
